-- liquibase formatted sql

-- changeset script:1
-- comment: Creations table personas
create table personas (
    id_persona integer generated by default as identity,
    apellido varchar(255),
    fecha_nacimiento timestamp(6),
    nombre varchar(255),
    numero_identificacion integer,
    id_tipo_identificacion_fk integer,
    id_tipo_persona_fk integer,
    primary key (id_persona)
);

-- changeset script:2
-- comment: Creations table tipo_personas
create table tipo_personas (
    id_tipo_persona integer generated by default as identity,
    tipo varchar(255),
    primary key (id_tipo_persona)
);

-- changeset script:3
-- comment: Creations table tipos_identificacion
create table tipos_identificacion (
    id_tipo_identificacion integer generated by default as identity,
    descripcion varchar(20),
    nombre varchar(255),
    primary key (id_tipo_identificacion)
);

-- changeset script:4
-- comment: Creations table agendas
create table agendas (
    id_agenda integer generated by default as identity,
    id_clase_fk integer,
    id_estudiante_fk integer,
    id_profesor_fk integer,
    primary key (id_agenda)
);

-- changeset script:5
-- comment: Creations table clases
create table clases (
    id_clase integer generated by default as identity,
     nombre varchar(255),
     primary key (id_clase)
 );

-- changeset script:6
-- comment: Creations table inser tipos_identificacion
insert into tipos_identificacion (descripcion, nombre) values
    ('Cedula','CC'),
    ('Tarjeta Identidad','TT'),
    ('NIT','NIT');

-- changeset script:7
-- comment: Creations table inser tipo_personas
insert into tipo_personas (tipo) values
    ('Estudiante'),
    ('Profesor');


-- changeset script:8
-- comment: Creations table inser tipo_personas
insert into personas (nombre, apellido, fecha_nacimiento, numero_identificacion, id_tipo_identificacion_fk, id_tipo_persona_fk) values
    ('Maria', 'Velazques', '2023-07-31T03:15:44.859' ,951236548 ,1 , 2),
    ('Carlo', 'Zuluaga', '2023-07-31T03:15:44.859' ,1587563215 ,2 , 1);


